### ISSUE TITLE
Where does the config go?

### ISSUE THREAD

**Issue by dehuszar** [svgstore/broccoli-svgstore#1]
Hi there,

I tried installing in my Ember-CLI project.  I've added your example config to my Brocfile.js, and while I get no errors, I also get no output.  Is this designed to be run in Ember-CLI?

Perhaps I'm missing a step...

**Comment by jmarquis** [comment]
Are you merging the output tree into `module.exports`?

``` javascript
var svgstore = require("broccoli-svgstore");
var mergeTrees = require("broccoli-merge-trees");

// other trees are created here
// ...
// ...

var svgTree = svgstore(inputTree, {
  outputFile: "/assets/icons.svg"
});

module.exports = mergeTrees([someTree, anotherTree, svgTree]);
```

**Comment by ghost** [comment]
@dehuszar did you get anywhere with this? I recommend looking at https://github.com/salsify/ember-cli-svgstore if you haven't seen it already.

**Comment by dehuszar** [comment]
I did thanks!  I am using Ember-CLI-svgstore and it's working great.  Thanks for checking back in with me.
