### ISSUE TITLE
Use of this module (via ember-cli-svgstore) breaks ember-cli hot css reloads

### ISSUE THREAD

**Issue by jesseditson** [svgstore/broccoli-svgstore#11]
According to this issue: https://github.com/salsify/ember-cli-svgstore/issues/4 (and this thread http://discuss.emberjs.com/t/hot-reloading-css-reloads-complete-page/10729/4), using ember-cli-svgstore breaks css hot reloading, and needs a fix in this repo to resolve.

The assumption the linked issue makes is that the broccoli cache is busted by this module, which makes intuitive sense. I'll try swapping in `broccoli-caching-writer` and report back here.

**Comment by BrianSipple** [comment]
Closing this for now (see comments in #12)
