### ISSUE TITLE
Option to remove inline styles from SVGs

### ISSUE THREAD

**Issue by tomwayson** [svgstore/broccoli-svgstore#4]
It would be nice if there was an option to remove inline styles (like fill, stroke, etc) that can prevent CSS styles from being applied to the SVGs?

For example: https://github.com/FWeinb/grunt-svgstore#optionscleanup-since-026

**Comment by BrianSipple** [comment]
Hey @tomwayson. There's currently an effort underway to build functionality like this into a [common, framework-agnostic svgstore](https://github.com/svgstore/svgstore/issues/1). I'm planning on implementing this feature there, among other things, and then I'll update this project to use svgstore directly after merging #8.

**Comment by BrianSipple** [comment]
@tomwayson This should now be possible after #13. Closing for now, but let me know if you have any issues.
