### ISSUE TITLE
New/additional maintainer

### ISSUE THREAD

**Issue by awaer** [svgstore/broccoli-svgstore#9]
This project appears to need a new maintainer. @BrianSipple has offered (#8) to take over maintenance moving forward and has multiple useful PRs. Can you (@jmarquis ) give him rights to this project?

**Comment by jmarquis** [comment]
Apologies for the delay on my end.

I've been in contact with @BrianSipple and he has offered to maintain this project going forward. He is now a repo admin with full permissions to manage things as necessary.

I plan to contribute to this project again in the near future but don't want to get in the way of people who want to make improvements in the meantime. Many thanks to everyone who has been participating in PRs and issues, and again I apologize for the delay in making this much-needed change.
